name: PHP Lint

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: PHP Lint
      run: |
        pwd
        if [ -f composer.lock ]; then composer install; fi
        git submodule update --init --recursive
        php ./lint.php
